LIBPATH=/opt/intel/Compiler/11.1/064/mkl/lib/em64t
LIBS= \
  $(LIBPATH)/libmkl_scalapack_lp64.a \
  $(LIBPATH)/libmkl_intel_lp64.a \
  $(LIBPATH)/libmkl_blacs_openmpi_lp64.a \
  $(LIBPATH)/libmkl_core.a  \
  $(LIBPATH)/libmkl_sequential.a \
  $(LIBPATH)/libmkl_core.a  \
  $(LIBPATH)/libmkl_sequential.a \
  $(LIBPATH)/libmkl_core.a  \
  -lpthread

LIBS=-mkl
dsyev.ex: dsyev.f90
	ifort -o dsyev.ex dsyev.f90  $(LIBS)


