#!/bin/bash -x
#SBATCH --job-name="hybrid"
#comment= "glorified hello world"
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks=8
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=10:00:00
#SBATCH -o ascript_out.%j

## Go to the directoy from which our job was launched
cd $SLURM_SUBMIT_DIR
JOBID=`echo $SLURM_JOBID`
mkdir ascript_$JOBID
cd ascript_$JOBID

echo "trying runjob"
export OMP_NUM_THREADS=4
printenv OMP_NUM_THREADS > env_$JOBID
srun --label  $SLURM_SUBMIT_DIR/docol.exe > output
echo "got to the bottom"

