#!/bin/bash

STRDIR=`pwd`

subs="100.html 200.html 300.html 400.html 800.html 1000.html 1400.html 1700.html 2000.html"

cd $STRDIR

mkdir -p two
dirs=`grep -l NODES=2 */summary/index.html | sed s,/summary/index.html,,`
echo $dirs
cp -r $dirs two
cd two

BASE=`echo $dirs | cut -f 1 -d ' '`
REST=`echo $dirs | sed "s/$BASE//"`

for D2 in $REST ; do
  echo $BASE $D2
  mkdir -p $D2/diff
  for s in $subs ; do 
     $STRDIR/diff.py $BASE/summary/$s $D2/summary/$s > $D2/diff/$s
  done
done

cd $BASE/summary
for l in `ls *0.html | sort -n` ; do  $STRDIR/getmin.py $l; done > $STRDIR/two_nodes

cd $STRDIR

mkdir -p four 
dirs=`grep -l NODES=4 */summary/index.html | sed s,/summary/index.html,,`
echo $dirs
cp -r $dirs four
cd four

BASE=`echo $dirs | cut -f 1 -d ' '`
REST=`echo $dirs | sed "s/$BASE//"`

for D2 in $REST ; do
  echo $BASE $D2
  mkdir -p $D2/diff
  for s in $subs ; do 
     $STRDIR/diff.py $BASE/summary/$s $D2/summary/$s > $D2/diff/$s
  done
done

cd $BASE/summary
for l in `ls *0.html | sort -n` ; do  $STRDIR/getmin.py $l; done > $STRDIR/four_nodes

cd $STRDIR

mkdir -p eight 
dirs=`grep -l NODES=8 */summary/index.html | sed s,/summary/index.html,,`
echo $dirs
cp -r $dirs eight
cd eight

BASE=`echo $dirs | cut -f 1 -d ' '`
REST=`echo $dirs | sed "s/$BASE//"`

for D2 in $REST ; do
  echo $BASE $D2
  mkdir -p $D2/diff
  for s in $subs ; do 
     $STRDIR/diff.py $BASE/summary/$s $D2/summary/$s > $D2/diff/$s
  done
done

cd $BASE/summary
for l in `ls *0.html | sort -n` ; do  $STRDIR/getmin.py $l; done > $STRDIR/eight_nodes


cd $STRDIR

#merge the diff files
set=`find . -name "diff"`
echo $set
for s in $set ; do
   cd $s
   ~/bin/mhtml $subs > merge.html
   cd $STRDIR
done

cd $STRDIR

#merge the summary files
set=`find . -name "summary"`
echo $set
for s in $set ; do
   cd $s
   ~/bin/mhtml $subs > merge.html
   cd $STRDIR
done

cd $STRDIR


#tree -H http://localhost/~$USER/petsc --dirsfirst -v -I "notes|stdout|100|200|300|400|800|1000|1400|1700|2000|100.html|200.html|300.html|400.html|800.html|1000.html|1400.html|1700.html|2000.html|env|script|slurm*|times|ex16*|p*|*.py|buildit|*tgz|tymer|makefile|merge" > summary.html  
#tree -H http://localhost/~$USER/petsc --dirsfirst -v -I notes > index.html  
#find . -type d -exec chmod 755 {} \; 
#find . -type f -exec chmod 644 {} \;



