#!/bin/bash
#####  for d in `ls | grep ^2` ; do ./postit $d ; done
START=`pwd`
cd $1
echo $1
#export NODES=`grep nodes script | sed "s/#SBATCH//" | sed "s/--//"`
export NODES=`grep SLURM_JOB_NUM_NODES env | sed "s/SLURM_JOB_NUM_//"`
export DATE=`head -1 times | cut -f 2,3,4,5,6 -d" "`
export HEAD=`echo $NODES $DATE`
dirs="100 200 300 400 800 1000 1400 1700 2000"
for d in $dirs ; do echo $d ; cd $d ; python $START/postit.py > summary ; export mat=`expr $d \* $d` ; export HEADER=`echo size= $mat $HEAD` ; greenbar summary > summary.html ; rm summary ;cd .. ; done
mkdir summary
for d in $dirs ; do echo $d ; mv $d/summary.html summary/$d.html  ; done
cd summary
tree -H . -T "$HEAD" > index.html
cd $START


