#!/bin/bash 
#SBATCH --job-name="hybrid"
#SBATCH --nodes=1
#SBATCH --export=ALL
#SBATCH --time=00:10:00
#SBATCH --account=hpcapps
#SBATCH --partition=debug


#set up our environment
umask 027
module purge
ml comp-intel/2018.0.3 intel-mpi/2018.0.3           

#make a dir and go there, copy our script
mkdir -p $SLURM_JOB_ID/ajob
cat $0 > $SLURM_JOB_ID/script
cd $SLURM_JOB_ID/ajob


#get hello world and compile it with mpicc 
wget -q https://raw.githubusercontent.com/timkphd/examples/master/hybrid/phostone.c 
mpicc -fopenmp phostone.c -o phostone

#run hello world for 10 seconds 4 threads, 4 mpi tasks
export OMP_NUM_THREADS=4
srun -n 4 ./phostone -t 10 -F  > output

