#!/bin/bash 
#SBATCH --job-name="hybrid"
#SBATCH --nodes=1
#SBATCH --export=ALL
#SBATCH --oversubscribe
#SBATCH --time=01:00:00
#SBATCH --account=hpcapps
#SBATCH --exclusive=user
#SBATCH --partition=debug


mkdir -p $SLURM_JOB_ID/ajob
cat $0 > $SLURM_JOB_ID/script
cd $SLURM_JOB_ID/ajob

module purge
ml comp-intel/2018.0.3 intel-mpi/2018.0.3           
export umask 027

cp ~/examples/hybrid/phostone.c .
mpiicc -fopenmp phostone.c -o phostone

export OMP_NUM_THREADS=4
srun -n 4 ./phostone - t 10 -F  > output

