install.packages("ggplot2", repos="http://cran.r-project.org")
install.packages("ggmap", repos="http://cran.r-project.org")
install.packages("maps", repos="http://cran.r-project.org")
install.packages("mapdata", repos="http://cran.r-project.org")
install.packages("dplyr", repos="http://cran.r-project.org")
install.packages("doParallel", repos="http://cran.r-project.org")
install.packages("gplots", repos="http://cran.r-project.org")
install.packages("foreach", repos="http://cran.r-project.org")
install.packages("tictoc", repos="http://cran.r-project.org")
install.packages("stringr", repos="http://cran.r-project.org")
install.packages("doMC", repos="http://cran.r-project.org")
install.packages("devtools", repos="http://cran.r-project.org")
devtools::install_github("IRkernel/IRkernel")

