#!/bin/bash -e
#SBATCH --job-name="array_job"
#SBATCH --nodes=1
##SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
###### sending output to /dev/null will suppress it
###### this is a good idea for array jobs lest it
###### create extra output for each subjob
##SBATCH -o /dev/null
#SBATCH --partition=standard
#SBATCH --account=hpcapps

#SBATCH --export=ALL
#SBATCH --array=1-24 
#SBATCH --exclusive=user
#SBATCH --mem=20G


module load python

# make a directory for the job and subjob
mkdir -p $SLURM_ARRAY_JOB_ID/$SLURM_ARRAY_TASK_ID
# go there
cd $SLURM_ARRAY_JOB_ID/$SLURM_ARRAY_TASK_ID

# Get our input
export input=`head -n $SLURM_ARRAY_TASK_ID $SLURM_SUBMIT_DIR/list | tail -1`
echo $input > input

# Run our job
#eval $SLURM_SUBMIT_DIR/invertp.py `cat input` > output
$SLURM_SUBMIT_DIR/invertp.py `cat input` > output
