#!/usr/bin/python
import sys
import os
header="""
<!DOCTYPE html>
<html lang="en">
<head>    
	<meta charset="utf-8" />
	<title>Untitled</title>

<style>
	BODY { background-color: #DDD; }

	.greenbar
	{
		font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
		border-collapse: collapse;
		width: 100%;
	}
	
	.greenbar th
	{
		font-size: 1.4em;
		text-align: center;
		padding-top: 5px;
		padding-bottom: 4px;
		background-color: #A7C942;
		color: #fff;
	}

	.greenbar td
	{
		font-size: 1.0em;
		border: 1px solid #98bf21;
		text-align: right;
		padding: 3px 7px 2px 2px;
	}
	
	.greenbar tr:nth-child(odd) td
	{
		color: #000;
		background-color: #EAF2D3;
	}
	
	.greenbar tr:nth-child(even) td
	{
		color: #000;
		background-color: #ffffff;
	}
	.greenbar td:nth-child(300n+0)
	{
		text-align: left;
	}
	.greenbar td:nth-child(400n+0)
	{
		text-align: center;
	}
	.greenbar td:nth-child(500n+0)
	{
		text-align: right;
	}
	
	.bluebar
	{
		font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
		border-collapse: collapse;
		width: 100%;
	}
	
	.bluebar th
	{
		font-size: 1.4em;
		text-align: left;
		padding-top: 5px;
		padding-bottom: 4px;
		background-color: #646490;
		color: #fff;
	}

	.bluebar td
	{
		font-size: 1.0em;
		border: 1px solid #0000ff;
		padding: 3px 7px 2px 2px;
	}
	
	.bluebar tr:nth-child(odd) td
	{
		color: #000;
		background-color: #DCDCFF;
	}
	
	.bluebar tr:nth-child(even) td
	{
		color: #000;
		background-color: #ffffff;
	}
	
	bluebar td:nth-child(300n+0)
	{
		text-align: left;
	}
	.bluebar td:nth-child(400n+0)
	{
		text-align: center;
	}
	.bluebar td:nth-child(500n+0)
	{
		text-align: right;
	}
	.narrow
	{
		width: 25%;
		text-align: center;
	}


</style>
</head>
<body>
XXXXXXXX
"""
data="""run	nodes	tpn	total<br>tasks	build	time
out16_128	8	16	128	build4	1.00567062124997619
out16_128	8	16	128	build6	1.00576529374995971
out16_128	8	16	128	build3	0.409357148750004285
out16_128	8	16	128	build5	0.352833823750074771
out16_128	8	16	128	build7	0.401254814999902010
out16_128	8	16	128	xxxxxx	0.271314396875002473
&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;
out32_256	8	32	256	build4	0.601276714999983142
out32_256	8	32	256	build6	0.604261700624988407
out32_256	8	32	256	build3	0.289758434375016805
out32_256	8	32	256	build5	0.257383043749996432
out32_256	8	32	256	build7	0.284165476249995663
out32_256	8	32	256	xxxxxx	0.202702161875002673
"""
title=os.getenv("HEADER")
if (title):
	header=header.replace("XXXXXXXX","<h3>"+title+"</h3>")
	header=header.replace("Untitled",title)
else:
	header=header.replace("XXXXXXXX","")
color="blue"
if(sys.argv[0].find("green") > -1):
	color="green"
else:
	color="blue"
if len(sys.argv) > 1:
	f=open(sys.argv[1])
	data=f.read()
print(header)
if len(sys.argv) == 1 :
	sys.stderr.write('export HEADER="title to set title"')
if len(sys.argv) > 2:
	color=sys.argv[2]
if(color=="green"):
	print('<table class="greenbar">')
else:
	print('<table class="bluebar">')
lines=data.split("\n")
#print lines
head=lines[0]
head=head.replace("\t","</th><th>")
head="<tr><th>"+head+"</th></tr>"
print(head)
for l in lines[1:]:
	if len(l) < 1 :
		continue
	l=l.replace("\t","</td><td>")
	l='<tr><td>'+l+"</td></tr>"
	print(l)
print("</table>")
print("</body>")
print("</html>")
