#!/usr/bin/env python3
import sys
import os
if len(sys.argv) > 1 :
    job=sys.argv[1]
else:
    command="squeue -hu $USER"
    f2=os.popen(command,"r")
    job=f2.read()
    job=job.split()
    job=job[0]
command='squeue -u $USER -j $1 -ho %N'
command=command.replace("$1",job)
f2=os.popen(command,"r")
list=f2.read()
f2.close()
command="scontrol show hostnames $list"
command=command.replace("$list",list)
f2=os.popen(command,"r")
long=f2.readlines()
for l in long:
    l=l.strip()
    print(l)
    command="ssh $l cat /proc/meminfo | grep Mem"
    # idea: cat /proc/1234/stat
    # see  man proc for a description of what is in /proc
    command=command.replace("$l",l)
    f2=os.popen(command,"r")
    lines=f2.readlines()
    for l in lines:
        print(l.strip())
