#!/bin/bash -f
ME=`whoami`@67.127.129.109
ME=`whoami`@`hostname`
HN=`ifconfig | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sed "s/[a-z]//g" | sed "s/$(printf '\t ' )//" | cut -f 1 -d" " | tail -n 1`
HN=`hostname -f`
#ME=`whoami`@`curl -s http://peloton.sdsc.edu/~tkaiser/cgi-bin/hits4.cgi | grep "mbpro"   | cut -d" " -f 4 | sed -e s/\<..\>//g -e s/\<...\>//g`
ME=`whoami`@$HN
LD=$ME:`pwd`
if [ $# -ne 0 ]
then
  for z in  $* ; do
    if [[ $z == \/* ]]
    then
        echo $ME:$z
    else
    echo $LD"/"$z
    fi
  done 
else
  echo $LD
fi

