#!/bin/bash -e
#SBATCH --job-name="bot_job"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --time=00:05:00
##SBATCH -o outz-%j
##SBATCH --share
#SBATCH --export=ALL
#SBATCH --account=hpcapps
#SBATCH --partition=debug


#conda activate tfgpu
#conda install mpi4py
#conda install matplotlib
#conda install Tornado

tar -xzf laser.tgz
rm -rf laser/*png
mpirun -n 4 -hosts=$SLURM_NODELIST ./simple.py < flist
