#!/bin/bash
#PBS -l nodes=2:ppn=8
#PBS -l walltime=08:00:00
#PBS -N test_1
#PBS -o outx.$PBS_JOBID
#PBS -e errx.$PBS_JOBID
#PBS -r n
#PBS -V 
##PBS -m abe
##PBS -M tkaiser@mines.edu
#-----------------------------------------------------
cd $PBS_O_WORKDIR

# get a short  list of all of my nodes
sort -u  $PBS_NODEFILE > mynodes.$PBS_JOBID

export MYPROGRAM=c_ex01
echo "running" $PBS_O_WORKDIR/$MYPROGRAM
mpiexec -np 16 $PBS_O_WORKDIR/$MYPROGRAM

export MYPROGRAM=f_ex01
echo "running" $PBS_O_WORKDIR/$MYPROGRAM
mpiexec -np 16 $PBS_O_WORKDIR/$MYPROGRAM



