#!/bin/bash
##SBATCH --job-name="atest"
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=8
#SBATCH --time=00:02:00
#SBATCH -o /scratch/%u/%j.out
#SBATCH -e /scratch/%u/%j.err
##SBATCH --partition=debug
##SBATCH --account=hpcapps
##SBATCH --mail-type=ALL
##SBATCH --mail-user=joeuser@nrel.gov

# Setup
export BASE=$SLURM_SUBMIT_DIR
mkdir -p $BASE/$SLURM_JOB_ID
cd $BASE/$SLURM_JOB_ID

# Save info
cat $0   > $SLURM_JOB_ID.script
printenv > $SLURM_JOB_ID.env

# Get and build glorified "Hello World"
module load intel-oneapi-mpi
curl -s https://raw.githubusercontent.com/timkphd/examples/master/hybrid/pstream.c -o pstream.c
mpicc -fopenmp pstream.c -o  pstream

echo "First run"
export OMP_NUM_THREADS=1
srun ./pstream -F -D -t 5
echo "Second run:"
export OMP_NUM_THREADS=18
srun --nodes=1 --ntasks=4 --ntasks-per-node=4 ./pstream -F -D -t 5 > pstream.out

mv $SLURM_SUBMIT_DIR/$SLURM_JOB_ID.out .
mv $SLURM_SUBMIT_DIR/$SLURM_JOB_ID.err .

