#!/bin/bash
#PBS -l nodes=1:ppn=8 
#PBS -l walltime=00:10:00 
#PBS -N testIO 
#PBS -o stdout 
#PBS -e stderr 
#PBS -r n 
#PBS -V 
#----------------------------------------------------- 
cd $PBS_O_WORKDIR 

#save a nicely sorted list of nodes 
sort -u $PBS_NODEFILE  > mynodes.$PBS_JOBID 
cp mynodes.$PBS_JOBID ~/.ddt/nodes

#for openmpi
mpiexec -n 4 ./stc_06.g < st.in


