#!/usr/bin/bash
#SBATCH --job-name="start_vasp"
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:02:00
#SBATCH --partition=debug

module reset
ml oneapi/2025.3.1  intel-oneapi-mpi
mpicc -fopenmp phostone.c -o phost_icc

export OMP_NUM_THREADS=1

for l in `seq 0 13 91`  ; do 
  UB=`echo $l + 12 | bc`
  echo core range $l $UB
  MASK=`./newmask.py $l $UB`
  srun -n 13 --threads-per-core=1 --cpu-bind=mask_cpu:$MASK ./phost_icc  -F  | egrep "^task|^0" | sort -nk6,6
done
