#!/bin/bash
#PBS -l nodes=2:ppn=8
#PBS -l walltime=08:00:00
#PBS -N test_1
#PBS -o outx.$PBS_JOBID
#PBS -e errx.$PBS_JOBID
#PBS -r n
#PBS -V 
##PBS -m abe
##PBS -M tkaiser@mines.edu
#-----------------------------------------------------
cd $PBS_O_WORKDIR

# get a short and full list of all of my nodes
sort -u  $PBS_NODEFILE > mynodes.$PBS_JOBID
sort   $PBS_NODEFILE > allmynodes.$PBS_JOBID

# run each program, one after the other

for P in c_ex00 f_ex00 info_p info_c info_f ; do
  export MYPROGRAM=$P
  echo "running" $PBS_O_WORKDIR/$MYPROGRAM
  mpiexec -np 16 $PBS_O_WORKDIR/$MYPROGRAM
done

