#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=02:00:00
#PBS -N testIO
#PBS -A account
#PBS -o stdout
#PBS -e stderr
#PBS -V
##PBS -m abe
##PBS -M tkaiser@mines.edu
#----------------------
cd $PBS_O_WORKDIR
mpiexec -np 8 ./c_ex00
