#!/usr/bin/bash
export PATH=~/piubuntu/examples/tims_tools:$PATH
cd ~/piubuntu
tymer ~/piubuntu/phase02.time installing spack x 3
export I09876=/nopt/spk


if [ -z ${I09876+x} ]; then
    ED=`date +"%y%m%d"a`
    export I09876=/nopt/apps/$ED
    echo Install directory not set - defaulting to $I09876
else
    echo Install directory - $I09876
fi

cd ~/piubuntu
mkdir spackit
cd spackit
export STRTDIR=`pwd`
for l in level00 level01 level02 ; do
  mkdir $l
  cd $l
  git clone https://github.com/spack/spack.git
  #cp ~/piubuntu/examples/spack/swift/$l/spack/etc/spack/defaults/*  spack/etc/spack/defaults
  cp ~/piubuntu/swift/$l/spack/etc/spack/defaults/*  spack/etc/spack/defaults
  cd ..
done

export EDTFILES=`grep -l -r I09876 .`

for l in $EDTFILES ; do
	echo $l
	sed --in-place s,I09876,$I09876, $l
done

cat << END >> ~/myenv

spackit00() {
	source $STRTDIR/level00/spack/share/spack/setup-env.sh
}
spackit01() {
	source $STRTDIR/level01/spack/share/spack/setup-env.sh
}
spackit02() {
	source $STRTDIR/level02/spack/share/spack/setup-env.sh
}

END
tymer ~/piubuntu/phase02.time installing lmod

spackit00() {
	source $STRTDIR/level00/spack/share/spack/setup-env.sh
}

spackit00
spack install lmod

tymer ~/piubuntu/phase02.time installing python@3.8.0


# at least one version below current
spack install python@3.8.0

tymer ~/piubuntu/phase02.time  updating spack yaml files

arch=`spack find --format {arch} lmod`
echo $arch

gccv=`ls  /nopt/spk/level00 | grep gcc | tail -1`

lpath=`find /nopt/spk/level00  -type d -name init`

lmodinit=$lpath/bash

echo $lmodinit

echo ". "  $lmodinit >> $HOME/myenv

cd ~/piubuntu/spackit

export EDTFILES=`find $HOME/spackit -name upstreams.yaml`

for l in $EDTFILES ; do
	echo $l
	sed --in-place s,ARCH,$arch, $l
done

for l in $EDTFILES ; do
	echo $l
	sed --in-place s,GCC,$gccv, $l
done

tymer ~/piubuntu/phase02.time done
