both: two three

two:
	make -f make2

three:
	make -f make3

clean:
	rm -rf  test2_c   test2_f    test_c    test_f *mio.mines.edu

tar:
	tar -cf fft.tar batch1  make2  make3  makefile  test2.c  test2.f  test.c  test.f90
