#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:01:00
#PBS -N testIO
#PBS -o out.$PBS_JOBID
#PBS -e err.$PBS_JOBID
#PBS -V
##PBS -m abe
##PBS -M joeminer@mines.edu
#----------------------
cd $PBS_O_WORKDIR
sort -u $PBS_NODEFILE > shortlist
mpiexec -n 8 c01 > myjob.$PBS_JOBID
