#!/bin/bash
##PBS -l nodes=1:ppn=8
#PBS -l nodes=1
#
#PBS -W x=NACCESSPOLICY:SINGLEUSER
#PBS -l walltime=24:00:00
#PBS -N testIO
#PBS -o outx8.$PBS_JOBID
#PBS -e errx8.$PBS_JOBID
#PBS -V 
#PBS -m abe
#PBS -M joeuser@mines.edu
#-----------------------------------------------------
cd $PBS_O_WORKDIR

sort -u  $PBS_NODEFILE > mynodes.$PBS_JOBID

export INPUT=sinput
export APP=fillmemc

sort -u  $PBS_NODEFILE >  $APP.$INPUT.$PBS_JOBID
      
./$APP  < $INPUT >> $APP.$INPUT.$PBS_JOBID
