#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:02:00
#PBS -N testIO
#PBS -o out.$PBS_JOBID
#PBS -e err.$PBS_JOBID
#PBS -V
#PBS -m abe
#PBS -M joeuser@mines.edu
#----------------------
cd $PBS_O_WORKDIR
mpiexec -n 8 ./c_ex00 > myout.$PBS_JOBID
