#!/bin/bash -e
#SBATCH --job-name="array_job"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --time=48:00:00
#SBATCH -o outz-%j
##SBATCH -e errz-%j
##SBATCH --exclusive
#SBATCH --share
#SBATCH --export=ALL

##SBATCH --mem=1000

#----------------------
# example invocation
# sbatch --array=1-18 array

module purge
module load StdEnv
module load PrgEnv/python/gcc/2.7.11

cd $SLURM_SUBMIT_DIR

if [[ $SLURM_ARRAY_JOB_ID ]] ; then
	JOB_ID=$SLURM_ARRAY_JOB_ID
	SUB_ID=$SLURM_ARRAY_TASK_ID
else
	JOB_ID=$SLURM_JOB_ID
	SUB_ID=0
fi

export FLIST=list
export DOPRINT=yes
#export DOPRINT=no

#Make our directories if needed
for x in `cat $FLIST` ; do mkdir -p $x ; done


srun -n 2 ./dummy

wait




