#!/bin/bash
#PBS -l nodes=1:ppn=8:gpu
#PBS -l walltime=00:01:00
#PBS -N testIO
#PBS -o stdout
#PBS -e stderr
#PBS -V
#PBS -m abe
##PBS -M joeminer@mines.edu
#----------------------
cd $PBS_O_WORKDIR
sort -u $PBS_NODEFILE > shortlist
export NGPU=`./gpucount`

GPUS=`seq $NGPU`
echo $GPUS
for G in $GPUS ; do
	/opt/development/exp/mpi/builds/1.5.1/pg-11.5_posix/bin/mpiexec -np $G ./tmpi
done
for G in $GPUS ; do
	export OMP_NUM_THREADS=$G
	./topenmp
done





