#!/bin/bash
unset OLD_DIR
export NEW_DIR=job1
jid=`sbatch old_new | awk '{print $NF }'`
echo $jid
 
for job in job2 job3 job4 job5 ; do
  export OLD_DIR=$NEW_DIR
  export NEW_DIR=$job
  jid=`sbatch --dependency=afterok:$jid old_new | awk '{print $NF }'`
  echo $jid
done

