#!/bin/bash 
#SBATCH --job-name="version"
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=01:00:00
#SBATCH --account=hpcapps
#SBATCH --partition=debug
#SBATCH -e version
#SBATCH -o version

ml forge
source /kfs2/projects/hpcapps/tkaiser/p311/bin/activate
which python


rm -rf *map *json *dat *profile *PROFILE
map --profile  srun -n 3  python dompimem.py
map --export dompimem.json  dompimem*map
./dojson.py dompimem


map --profile python domem.py
map --export domem.json domem*map
./dojson.py domem

mprof run domem.py
mv mprofile* domem.profile


map --profile python quake.py
map --export quake.json quake*map
./dojson.py quake

mprof run quake.py
mv mprofile* quake.profile

#post process so everything is in seconds and GB

for p in `ls *profile` ; do
  FILE=`echo $p | sed "s/.profile//"`
  tail -n +2 $FILE.profile  > tmp
  st=`head -1 tmp | awk '{print $3}'`
  cat tmp | awk -v var=$st '{print $3-var,$2/1000}' > $FILE.PROFILE
  rm tmp
done


for p in `ls *map` ; do
	FILE=`echo $p | sed "s/.map//"`
	echo $FILE
	map --export $FILE.json $FILE.map
	./dojson.py $FILE
done





