#!/bin/bash 
#SBATCH --job-name="flow"
#SBATCH --nodes=1
#SBATCH --export=ALL
#SBATCH --oversubscribe
#SBATCH --time=00:10:00
#SBATCH --partition=debug
#SBATCH --account=hpcapps

module purge
ml intel-mpi

if [ -z ${EXE+x} ]; then export EXE=c_ex00 ; fi
echo "running " $EXE 

srun -n 4 ./$EXE


