#!/bin/bash -x
#SBATCH --job-name="hello"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks=16
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:01:00

#module load StdEnv

# Go to the directoy from which our job was launched
cd $SLURM_SUBMIT_DIR

# run an application
srun $SLURM_SUBMIT_DIR/c_ex01
srun $SLURM_SUBMIT_DIR/f_ex01

