#!/bin/bash
#SBATCH --job-name="hello"
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:20:00
#SBATCH --partition=debug
#SBATCH --account=hpcapps

cd $SLURM_SUBMIT_DIR

module purge
module use /nopt/nrel/apps/compilers/intel/2020.1.217/mods
module load compilervars 
module load mpivars
#Needed for this version of MPI and srun
export I_MPI_PMI_LIBRARY=/nopt/slurm/current/lib/libpmi.so

export nnodes=1
export tasks=2
RUN="srun               --nodes=$nnodes -n $tasks --cpus-per-task=$OMP_NUM_THREADS --cpu-bind=cores "

# run an application
$RUN ./c_ex02

