#!/bin/bash
#SBATCH --job-name="memory"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:05:00

# Go to the directoy from which our job was launched
cd $SLURM_SUBMIT_DIR

# We use multiple threads to fill up memory
export OMP_NUM_THREADS=16
# Time our run, just for fun
/opt/utility/tymer time.$SLURM_JOBID

srun -n 1  ./ftest > ftest.out.$SLURM_JOBID 2>&1

/opt/utility/tymer time.$SLURM_JOBID

srun -n 1  ./test > test.out.$SLURM_JOBID 2>&1

/opt/utility/tymer time.$SLURM_JOBID
