#!/bin/bash
#SBATCH --job-name="mpi4py"
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:10:00
#SBATCH --partition=debug
#SBATCH --account=hpcapps

module load conda
source ~/conda_init
conda activate dompi
module load intel-mpi/2020.1.217
cd ~/examples/mpi/mpi4py
srun -n 2 ./ppong.py 


