#!/bin/bash
#SBATCH --job-name="mpi4py"
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=8 
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=00:10:00
#SBATCH --partition=debug
#SBATCH --account=hpcapps

module load conda
source ~/conda_init
conda activate dompi
module load intel-mpi/2020.1.217
#cd ~/examples/mpi/mpi4py
date
rm -rf parallel_test.hdf5
export SUB=0
srun   ./h5b.py -size=64M -count=1 -mb=256
rm -rf parallel_test.hdf5
export SUB=1
srun   ./h5b.py -size=64M -count=-1 -mb=256
rm -rf parallel_test.hdf5
export SUB=2
srun   ./h5b.py -size=128M -count=1 -mb=256
rm -rf parallel_test.hdf5
export SUB=3
srun   ./h5b.py -size=128M -count=-1 -mb=256
rm -rf parallel_test.hdf5
export SUB=4
srun   ./h5b.py -size=64M -count=4 -mb=256
rm -rf parallel_test.hdf5
export SUB=5
srun   ./h5b.py -size=128M -count=4 -mb=256


