#!/bin/bash
#SBATCH --job-name="ior"
#SBATCH --nodes=2
#SBATCH --exclusive
#SBATCH --export=ALL
#SBATCH --time=01:00:00
#SBATCH --partition=debug
##SBATCH --output=system_build
##SBATCH --error=system_build

#get our data (See simple.py for a description)
rm -rf laser*
wget https://github.com/timkphd/examples/raw/master/array/bot/laser.tgz 
tar -xzf laser.tgz
# get a list of input files
find . -name "l_*" | grep -v png > flist

#This version of python has mpi4py installed using intel mpi for the backend
module use /nopt/nrel/apps/220511a/modules/lmod/linux-centos7-x86_64/gcc/12.1.0/
ml python
ml intel-oneapi-mpi
srun -n 18 --tasks-per-node=9 ./simple.py < flist

